"""Time-ordered UUIDv7 generator.

Used only on the local (SQLite) path, where the database has no uuidv7()
function. On PostgreSQL the id is generated by the DB (server_default uuidv7()).
"""
import os
import time
import uuid


def uuid7() -> uuid.UUID:
    """Return a UUIDv7 (48-bit ms timestamp + random, version/variant tagged)."""
    unix_ms = int(time.time() * 1000)
    raw = bytearray(unix_ms.to_bytes(6, "big") + os.urandom(10))
    raw[6] = (raw[6] & 0x0F) | 0x70  # version 7
    raw[8] = (raw[8] & 0x3F) | 0x80  # RFC 4122 variant
    return uuid.UUID(bytes=bytes(raw))
