"""initial schema: users + feedbacks

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-01 00:00:00
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuidv7()"),  # generated by PostgreSQL
            primary_key=True,
        ),
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.UniqueConstraint("login", name="uq_users_login"),
    )

    op.create_table(
        "feedbacks",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuidv7()"),  # generated by PostgreSQL
            primary_key=True,
        ),
        sa.Column("topic", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),  # generated by PostgreSQL
            nullable=False,
        ),
    )
    op.create_index("ix_feedbacks_created_at", "feedbacks", ["created_at"])

    # Seed one admin so the app is usable out of the box (id filled by uuidv7()).
    # Provision further admins by hand via the exposed 5432 port.
    op.execute("INSERT INTO users (login, password) VALUES ('admin', 'password')")


def downgrade() -> None:
    op.drop_index("ix_feedbacks_created_at", table_name="feedbacks")
    op.drop_table("feedbacks")
    op.drop_table("users")
