import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { listWall, reactToIdea } from '../api/ideas.js'
import Button from '../components/Button.jsx'
import ErrorBanner from '../components/ErrorBanner.jsx'
import IdeaDialog from '../components/IdeaDialog.jsx'
import Logo from '../components/Logo.jsx'

const preview = (text) => text.length > 180 ? `${text.slice(0, 180).trim()}...` : text
export default function Wall() {
  const [page, setPage] = useState(1); const [data, setData] = useState({ items: [], total_pages: 0 }); const [selected, setSelected] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  async function load() { setLoading(true); setError(''); try { setData(await listWall(page)) } catch { setError('Не удалось загрузить идеи. Попробуйте снова.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [page])
  async function react(item, value) { try { const updated = await reactToIdea(item.id, value); setData((current) => ({ ...current, items: current.items.map((entry) => entry.id === updated.id ? updated : entry) })); setSelected((current) => current?.id === updated.id ? updated : current) } catch { setError('Не удалось сохранить оценку. Попробуйте снова.') } }
  return <div className="wrap"><main className="wall-page"><header className="wall-page__head"><div className="page-top"><Logo /><Link className="account-link" to="/admin" aria-label="Администратору">Администратору</Link></div><div className="wall-page__intro"><h1 className="compose__title">Стена идей</h1><p className="compose__lede">Делитесь идеями, которые делают работу проще, сервис лучше, а компанию сильнее.</p></div><div className="wall-nav"><nav className="section-nav" aria-label="Разделы"><Link className="section-nav__link is-active" to="/">Стена идей</Link></nav><div className="wall-page__actions"><Link className="btn btn--ghost" to="/submit?type=feedback">Оставить обратную связь</Link><Link className="btn btn--primary" to="/submit?type=idea">Предложить идею</Link></div></div></header><ErrorBanner message={error} />{error && <Button variant="ghost" onClick={load}>Попробовать снова</Button>}{loading ? <p className="wall-state">Загружаем идеи…</p> : !data.items.length ? <div className="empty"><p className="empty__title">Здесь пока нет идей</p><p>Предложите первую идею, которая поможет сделать работу лучше.</p><Link className="btn btn--primary" to="/submit?type=idea">Предложить идею</Link></div> : <div className="idea-grid">{data.items.map((item) => <article className="idea-card" key={item.id}><div className="idea-card__meta">{item.category && <span className="idea-card__category">{item.category}</span>}<span className="status status--accepted">Принята</span></div><h2>{item.topic || 'Без названия'}</h2><p>{preview(item.body)}</p><footer><span>{item.author_name ? `${item.author_name}${item.author_department ? `, ${item.author_department}` : ''}` : 'Анонимно'}</span><time>{new Date(item.created_at).toLocaleDateString('ru-RU')}</time></footer><div className="vote-panel" aria-label="Оценка"><span className="comments-count">Комментарии: {item.comments_count || 0}</span><div><button type="button" className={item.viewer_reaction === 1 ? 'vote is-active' : 'vote'} onClick={() => react(item, item.viewer_reaction === 1 ? 0 : 1)}>Поддерживаю <b>{item.likes}</b></button><button type="button" className={item.viewer_reaction === -1 ? 'vote is-active' : 'vote'} onClick={() => react(item, item.viewer_reaction === -1 ? 0 : -1)}>Не поддерживаю <b>{item.dislikes}</b></button></div></div><button type="button" className="idea-card__more" onClick={() => setSelected(item)}>Подробнее</button></article>)}</div>}{data.total_pages > 1 && <div className="pager"><Button variant="ghost" disabled={page === 1} onClick={() => setPage((current) => current - 1)}>Назад</Button><span className="pager__label">{page} из {data.total_pages}</span><Button variant="ghost" disabled={page === data.total_pages} onClick={() => setPage((current) => current + 1)}>Вперёд</Button></div>}<IdeaDialog idea={selected} onClose={() => setSelected(null)} onReact={react} /></main></div>
}
