import { useCallback, useEffect, useState } from 'react'
import Button from '../../components/Button.jsx'
import ErrorBanner from '../../components/ErrorBanner.jsx'
import { deleteIdea, leaderboard, listIdeas, updateIdeaStatus } from '../../api/ideas.js'
import { confirmManualAuthor } from '../../api/manualAuthors.js'
import { formatTimestamp } from '../../lib/datetime.js'
import ManualAuthorManager from './ManualAuthorManager.jsx'

const LABELS = { new: 'На рассмотрении', accepted: 'Принята', rejected: 'Отклонена' }
export default function IdeaList({ onLogout }) {
  const [status, setStatus] = useState('new'); const [data, setData] = useState({ items: [], total: 0, total_pages: 0 }); const [leaders, setLeaders] = useState([]); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [ideas, board] = await Promise.all([listIdeas({ page, status }), leaderboard()]); setData(ideas); setLeaders(board.winners) } catch (requestError) { setError(requestError.message); if (requestError.status === 401) onLogout() } finally { setLoading(false) } }, [onLogout, page, status])
  useEffect(() => { load() }, [load])
  async function moderate(id, nextStatus) { await updateIdeaStatus(id, { status: nextStatus }); load() }
  async function remove(id) { if (window.confirm('Удалить идею? Восстановить её после удаления не получится.')) { await deleteIdea(id); load() } }
  async function confirmAuthor(id) { try { await confirmManualAuthor(id); load() } catch (requestError) { setError(requestError.message) } }
  return <div className="wrap"><main className="admin"><header className="topbar"><div><p className="eyebrow">Администратор</p><h1 className="topbar__title">Модерация идей</h1></div><Button variant="ghost" onClick={onLogout}>Выйти</Button></header><ManualAuthorManager /><section className="toolbar"><div className="toolbar__group"><label className="label" htmlFor="idea-status">Статус</label><select id="idea-status" className="control" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="">Все</option>{Object.entries(LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="toolbar__spacer"/><Button variant="ghost" onClick={load}>Обновить</Button></section><ErrorBanner message={error} />{leaders.length > 0 && <section className="leaders"><strong>Лидеры недели</strong> {leaders.map((item) => `${item.author_name} (${item.accepted_count})`).join(', ')}</section>}<p className="count">{loading ? 'Загружаем…' : `Идей: ${data.total}`}</p>{!loading && !data.items.length ? <div className="empty"><p className="empty__title">Идей нет</p><p>Новые идеи сотрудников появятся здесь.</p></div> : data.items.map((idea) => <article className="item" key={idea.id}><div className="item__top"><p className="item__topic">{idea.topic || 'Без названия'} <span className="hint">{LABELS[idea.status]}</span></p><time className="item__time">{formatTimestamp(idea.created_at)}</time></div>{idea.category && <span className="idea-card__category">{idea.category}</span>}<p className="item__body">{idea.body}</p><p className="hint">{idea.author_name ? `${idea.author_name}${idea.author_company ? `, ${idea.author_company}` : ''}${idea.author_department ? `, ${idea.author_department}` : ''}` : 'Анонимно'}</p><div className="item__actions">{idea.author_name && !idea.author_bitrix_id && <Button variant="ghost" onClick={() => confirmAuthor(idea.id)}>Подтвердить автора</Button>}{idea.status !== 'accepted' && <Button variant="ghost" onClick={() => moderate(idea.id, 'accepted')}>Принять</Button>}{idea.status !== 'rejected' && <Button variant="ghost" onClick={() => moderate(idea.id, 'rejected')}>Отклонить</Button>}<Button variant="danger" onClick={() => remove(idea.id)}>Удалить</Button></div></article>)}{data.total_pages > 1 && <div className="pager"><Button variant="ghost" disabled={page === 1} onClick={() => setPage((current) => current - 1)}>Назад</Button><span className="pager__label">{page} / {data.total_pages}</span><Button variant="ghost" disabled={page === data.total_pages} onClick={() => setPage((current) => current + 1)}>Вперед</Button></div>}</main></div>
}
